apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-random-writer
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: writer
              image: ghcr.io/daniakd2003/test_task/s3-random-writer
              imagePullPolicy: IfNotPresent
              env:
                - name: AWS_REGION
                  value: eu-central-1
                - name: S3_BUCKET
                  value: s3-random-writer-data-f6c0abb0
                - name: S3_PREFIX
                  value: random
